### ISSUE TITLE
Bonus: Add capability to allow users to save Sample Point Feature Layer to AGOL GeoPlatform

### ISSUE THREAD

**Issue by tommckennon** [USEPA/Scribe-Data-View-Tool#7] opened 2019-12-28 21:07 UTC
Bonus: Add the capability to allow users to save Sample Point Feature Layer to AGOL GeoPlatform.

**Comment by jlherring** [comment] 2020-05-08 16:07
duplicate of #33

**Closed by jlherring** 2020-05-08 16:07 UTC
